### ISSUE TITLE
Better way to create an array like this

### ISSUE THREAD

**Issue by miguel-de-aXman** [dinuKumaradas/sampleCF#1]
https://github.com/dinuKumaradas/sampleCF/blob/fb07b0abb448c6122526387036274607ad3936a7/components/utilities.cfc#L26

Hi Dinu, 
How could you rewrite getDefaultList() such that it takes an integer variable. And that integer determines how many records are returned in the default query? e.g. getDefaultList(3) would be the same as returning:
`queryNew(data=[
                                {"id":1, "title":"Title 1", "author":"Author 1"}
                                , {"id":2, "title":"Title 2", "author":"Author 2"}
                                , {"id":3, "title":"Title 3", "author":"Author 3"}])`

**Comment by dinuKumaradas** [comment]
Thank you for your feedback.

Below changes has been added now.

- Made user defined function getDefaultList as parameterized. Default noOfRows value is 10.
- Added a filter function to the query based on the parameter passed.
- UDF getDefaultList now only will return 10 rows or based on the user input.

Best Reagrds,
Dinu
